# Generated by Django 5.0.6 on 2024-06-06 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room_created_at_room_updated_at_tag_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='room.tag'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('10:00~10:30', '10:00 - 10:30'), ('10:30~11:00', '10:30 - 11:00'), ('11:00~11:30', '11:00 - 11:30'), ('11:30~12:00', '11:30 - 12:00'), ('12:00~12:30', '12:00 - 12:30'), ('12:30~13:00', '12:30 - 13:00'), ('13:00~13:30', '13:00 - 13:30'), ('13:30~14:00', '13:30 - 14:00'), ('14:00~14:30', '14:00 - 14:30'), ('14:30~15:00', '14:30 - 15:00'), ('15:00~15:30', '15:00 - 15:30'), ('15:30~16:00', '15:30 - 16:00'), ('16:00~16:30', '16:00 - 16:30'), ('16:30~17:00', '16:30 - 17:00'), ('17:00~17:30', '17:00 - 17:30'), ('17:30~18:00', '17:30 - 18:00'), ('18:00~18:30', '18:00 - 18:30'), ('18:30~19:00', '18:30 - 19:00')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='room.room')),
            ],
        ),
    ]
